# CONFIGURACIÓN DE LA BASE DE DATOS (SUPABASE - PEST PLACE)

# Opción A: Conexión Directa (Requiere que tu internet admita IPv6)
# spring.datasource.url=jdbc:postgresql://db.lilmcztramhcdayuvzjn.supabase.co:5432/postgres?sslmode=require
# spring.datasource.username=postgres

# Opción B: Conexión con Pooler (Recomendado para evitar errores de IPv6)
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.lilmcztramhcdayuvzjn

spring.datasource.password=$P4ss_PetsPl@ce_#2026!
spring.datasource.driver-class-name=org.postgresql.Driver

# CONFIGURACIÓN DE JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true    
